name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo "VITE_GG_BEARER=${{ secrets.VITE_GG_BEARER }}" > .env
      - run: npm ci && npm run build
        env:
          VITE_GG_BEARER: ${{ secrets.VITE_GG_BEARER }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NIGHTCLUB_PAYMENT_TRACKING }}'
          channelId: live
          projectId: nightclub-payment-tracking